# Generated by Django 2.0.13 on 2019-09-20 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('FF', 'Fixed'), ('C', 'Choice'), ('F', 'Free')], default='FF', max_length=2)),
                ('position', models.IntegerField()),
                ('deleteAfterSave', models.BooleanField(default=False)),
                ('guide', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='main.Project')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('blocktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BlockType')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_blocks', to='main.Requirement')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('guide', models.TextField()),
                ('image', models.FileField(null=True, upload_to='images/')),
                ('block_types', models.ManyToManyField(to='main.BlockType')),
            ],
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('guide', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main.Template'),
        ),
        migrations.AddField(
            model_name='blocktype',
            name='text_blocks',
            field=models.ManyToManyField(to='main.TextBlock'),
        ),
    ]
